### PR TITLE
Split Stream and Struct traits into modules

### PR DESCRIPTION
**Pull request by gushromp**

### CODE REVIEW

**Comment by GreyCat** [comment]
@gushromp Thanks for your contribution! However, note that this Rust runtime is currently very experimental and there's no real compiler that generates output that would make use of it. If you want to pick up Rust target development, you're more than welcome to join in with ideas & code at https://github.com/kaitai-io/kaitai_struct/issues/22.

I wonder if @LogicAndTrick would review this PR?

**Comment by LogicAndTrick** [comment]
I'm not sure about splitting each individual trait into its own module, at the very most I would add them both into one module called `kaitai_struct`. But if you use the runtime as a crate, then the Cargo import already provides that namespacing for you, so isn't the crate's "root module" enough? I'd at least put some `pub use` statements into the root namespace so users don't have to chain namespaces like `use kaitai_struct::kaitai_struct::KaitaiStruct` which contains a lot of redundancy.

**Comment by gushromp** [comment]
@GreyCat Thanks! I've looked a bit into the issues that @LogicAndTrick has bumped into (with the references to the parent structures), and I think I have a vague idea on how to circumvent them but such a hierarchy is not pretty to implement in Rust (involves using Rc\<RefCell\<T\>\> everywhere).

@LogicAndTrick You're right, I now used `pub use` to reexport the stuff from the modules publicly, which would eliminate the redundant import while still keeping the code separated. But, if you feel like this adds unnecessary complexity and/or prefer keeping it as it was, I'll revert that :)

**Review by LogicAndTrick — APPROVED** [review]
Thanks for the changes, I think now this looks okay from my end. I'm fine with merging this in.

**Comment by GreyCat** [comment]
Thanks, everybody!

**Pull request merged**
